language: android
jdk: oraclejdk8
group: edge

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - platform-tools
    - extra-android-m2repository


env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8


script:
  - ./gradlew build assembleAndroidTest
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
 # - ./gradlew connectedCheck
